version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
#    depends_on:
#      - influx
    volumes:
      - $LOCAL_PATH/grafana:/var/lib/grafana
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=$GF_PANELS_DISABLE_SANITIZE_HTML
      - GF_SECURITY_DISABLE_GRAVATAR=$GF_SECURITY_DISABLE_GRAVATAR
      - GF_SECURITY_ALLOW_EMBEDDING=$GF_SECURITY_ALLOW_EMBEDDING
#      - GF_INSTALL_PLUGINS=$GF_INSTALL_PLUGINS
#      - GF_AUTH_PROXY_ENABLED=$GF_AUTH_PROXY_ENABLED
#      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
#      - GF_SERVER_ROOT_URL=$GF_SERVER_ROOT_URL
#      - GF_SERVER_SERVE_FROM_SUB_PATH=$GF_SERVER_SERVE_FROM_SUB_PATH
#      - GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER
#      - GF_AUTH_DISABLE_LOGIN_FORM=$GF_AUTH_DISABLE_LOGIN_FORM
#      - GF_AUTH_SIGNOUT_REDIRECT_URL=$APP_HOST/forward-auth/oidc/logout
#      - GF_AUTH_PROXY_HEADER_NAME=$GF_AUTH_PROXY_HEADER_NAME
#      - GF_AUTH_PROXY_HEADER_PROPERTY=$GF_AUTH_PROXY_HEADER_PROPERTY
#      - GF_AUTH_PROXY_HEADERS=$GF_AUTH_PROXY_HEADERS
#      - GF_AUTH_PROXY_AUTO_SIGN_UP=$GF_AUTH_PROXY_AUTO_SIGN_UP
#    labels:
#      - 'traefik.enable=true'
#      - 'traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)'
#      - 'traefik.http.services.grafana.loadbalancer.server.port=3000'
#      - 'traefik.http.middlewares.grafana-auth.forwardauth.address=http://carrier-auth/forward-auth/auth?target=header&scope=grafana'
#      - 'traefik.http.middlewares.grafana-auth.forwardauth.authResponseHeaders=X-WEBAUTH-USER, X-WEBAUTH-NAME, X-WEBAUTH-EMAIL'
#      - 'traefik.http.routers.grafana.middlewares=grafana-auth@docker'
#      - 'carrier=grafana'
    user: root
    ports: 
      - "3000:3000"
    container_name: graf